# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://pquinonezb.github.io/
baseurl: /pquinonezb.github.io/
title: "Pedro Quinonez"
author: "Pedro Quinonez"
description: "Pagina personal y CV"
avatar: profile.png
email: pedro.quinonez@gmail.com
github: pquinonezb # username
twitter: @quinonezbp
linkedin: https://www.linkedin.com/in/pquinonez/
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1

